### ISSUE TITLE
How are you so good

### ISSUE THREAD

**Issue by Steve-Dusty** [JustFast/toy#2]
This is unforbidden. You are too good. I forbid this. Please delete this repo

:ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand: :ok_hand:

**Comment by martin-esparragoza** [comment]
God gamer monke hed

**Comment by Steve-Dusty** [comment]
Steeceevevevveve Steve we. Steveeeevee enebebebe
